### ISSUE TITLE
module 'config' has no attribute 'profile'

### ISSUE THREAD

**Issue by happyfmy** [Tokeii0/LovelyMem#6]
python3 .\main.py
Traceback (most recent call last):
  File "C:\Users\123\Desktop\LovelyMem-0.4\main.py", line 736, in <module>
    lovelymem = Lovelymem()
  File "C:\Users\123\Desktop\LovelyMem-0.4\main.py", line 131, in __init__
    self.comboBox_profile.addItems(config.profile)
AttributeError: module 'config' has no attribute 'profile'

**Comment by Tokeii0** [comment]
看一下config.py中有没有以下内容
profile  = ['Win7SP1x64', 'Win7SP1x86', 'WinXPSP3x86', 'WinXPSP2x86', 'WinXPSP2x64']

**Comment by happyfmy** [comment]
ok 加上就好了
